project_name: example2

before:
  hooks:
    - rm -rf dist
    - go mod tidy
    - git push
    - git push --tags

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    flags:
      - -trimpath
    ldflags:
      - -s
      - -w

snapshot:
  name_template: "{{ incminor .Version }}-dev-{{.ShortCommit}}-{{.Timestamp}}"

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_checksums.txt"
  algorithm: sha256

brews:
  - name: example2
    tap:
      owner: ondrejsikademo
      name: homebrew-tap
    skip_upload: auto
    homepage: https://github.com/golang-training-examples/example2
    url_template: "https://github.com/golang-training-examples/example2/releases/download/{{ .Tag }}/{{ .ArtifactName }}"
    folder: Formula
    caveats: "How to use this binary: https://github.com/golang-training-examples/example2"
    description: "Example for Golang Training"
    install: |
      bin.install "example2"
    test: |
      system "#{bin}/example2"
